### ISSUE TITLE
Why this cookbook? 

### ISSUE THREAD

**Issue by spuder** [mmmorris1975/ulimit2#2]
There is another cookbook on the supermarket to manage ulimits. 

Why this one? What limitations does the other ulimit cookbook have?

**Comment by mmmorris1975** [comment]
I wasn't a fan of the attribute naming convention, I felt my way was cleaner, and it also allows group ulimit settings using the @group syntax.  The other cookbook also didn't support 'legacy' systems, and assumed that all systems supported ulimit configs in /etc/security/limits.d (not the case with Centos 6 and earlier, which only looks in /etc/security/limits.conf)

**Comment by spuder** [comment]
Great, thanks!
